version: '2'
services:
  nginx:
    build:
      context: ./env/docker/nginx
    container_name: dockerizedDjangoNginx01
    networks:
      # - nginx-proxy
      - docker-net
    environment:
      - VIRTUAL_HOST=example.com,www.example.com
      - LETSENCRYPT_HOST=example.com
      - LETSENCRYPT_EMAIL=cert@example.com
    volumes:
      - ./server/django_blog/static:/static
    links:
      - web
    ports: # MUST BE GONE, STILL HERE FOR DEMONSTRATION PURPOSES
      - "7000:80"

  web:
    extends:
      file: docker-compose.yml
      service: web

networks:
  docker-net:
  # nginx-proxy: # MUST BE UNCOMMENTED IN PROD AND https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion MUST BE INSTALLED ON SERVER
  #   external:
  #     name: nginxproxy_default
